name 'consul-replicate'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
description 'Application cookbook which installs and configures Consul Replicate'
long_description 'Application cookbook which installs and configures Consul Replicate'
issues_url 'https://github.com/johnbellone/consul-replicate-cookbook/issues'
source_url 'https://github.com/johnbellone/consul-replicate-cookbook'
version '0.5.1'

supports 'redhat', '>= 5.8'
supports 'centos', '>= 5.8'
supports 'ubuntu', '>= 12.04'

depends 'poise', '~> 2.6'
depends 'poise-archive', '~> 1.2'
depends 'poise-service', '~> 1.0'
depends 'rc', '~> 1.0'
